### ISSUE TITLE
F11 doesn't work, Nothing is in my StreamingSkybox live folder

### ISSUE THREAD

**Issue by timegate** [Stellarium/stellarium-unity#2]
Hello,
First of all, thank you for this wonderful project.

I'm trying to use StreamingSkybox.cs somehow, and I found logs below.

StreamingSkybox: pathbase=C:/Users/user/Desktop/try/New Unity Project/Assets/StreamingAssets\SkyBoxes/
SkyDataPath: C:/Users/user/Desktop/try/New Unity Project/Assets/StreamingAssets\SkyBoxes/live
Trying to get C:/Users/user/Desktop/try/New Unity Project/Assets/StreamingAssets\SkyBoxes/live\unityData.txt

When I do F11, it doesn't create unityData.txt and 6 png files in the live folder.
However, As I succeed to use the codes (https://github.com/idialab/StellariumUnity), it seems that those paths want to fetch the contents of the following paths.

C:\Users\YOU\Pictures\Stellarium\ (Here I have the 6 pngs!)
C:\Users\user\AppData\Roaming\Stellarium (Here I have unityData.txt!)

So I thought that maybe I could try 
1) changing skybox.ssc (to make Stellarium write images to the live folder)
2) changing StreamingSkybox.cs (overwrite SkydataPath, watcher.Path to the above paths)
3) set %STEL_SKYBOX_DIR% to C:/Users/user/Desktop/try/New Unity Project/Assets/StreamingAssets\SkyBoxes/live

I tried 2) and 3) but I had kept failed, I feel like I lost my way..
Could you please help me?

Thanks for this awesome work again!

**Comment by gzotti** [comment]
please read skybox.ssc. It contains lookup in paths which must be configured with environment variables. 
Oh wow, six years...
I hope you make some good use out of it. The combination has high usability in a narrow niche.

**Comment by FEXAQAQ** [comment]
Hello, I recently came into contact with Stellarium and wanted to run Stellarium on Unity, so I found this project. I am currently encountering the same problem, so I created the directory myself. Although there is no error message, there is no error message in the folder. anything. I would like to ask if there is something wrong with my startup method, or if I have missed any steps?

My steps are:
1. Create a new Unity project

2. Import: Unitypackage

3. Open: SampleScene

4. Pull the "FPSController" and "Stellarium" Prefab onto the scene.

5. Execution

PS: My English is not very good, please bear with me, thank you very much :) Finally, thank you to the author for providing a great project!

**Comment by gzotti** [comment]
And are you running Stellarium with RemoteControl in the background? Is there a connection?
Maybe you have to go into the C# files and enable a few log messages to find what's going on.

**Comment by FEXAQAQ** [comment]
Use Remote Control to run Stellarium in the background. Does this sentence refer to background execution in unity?

Or do I need to use other apps?


In other words, is this project a stand-alone executable project, or does it need to be paired with the Stellarium application to operate?

Thank you again :>

**Comment by gzotti** [comment]
Please read the research paper linked in the description. Yes, you need Stellarium with its RemoteControl plugin running and prepared to be requested by the Unity-based application before launching the Unity-based application, else there is no sky input to show in Unity.

**Comment by FEXAQAQ** [comment]
I understand, thank you very much.

I read it many times today. Maybe my English is not very good, so I misunderstood the meaning. I thought this was an independent project of unity haha.

Thank you very much for your patient explanation and have a nice day!
